import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Home from "./page";


export const metadata: Metadata = {
  title: "Trovia",
  description: "Generated by sumit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <Navbar/>
           <main className="relative overflow-hidden">
             {children}
           </main>
        <Footer/>
        </body>
    </html>
  );
}
